// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCclD7CKiVK0lL1UjemZzcJ-XHV37mMEqo',
    appId: '1:398771196913:web:f8bdb8c4dd1d87a1e02a50',
    messagingSenderId: '398771196913',
    projectId: 'metal-air-447106-m3',
    authDomain: 'metal-air-447106-m3.firebaseapp.com',
    storageBucket: 'metal-air-447106-m3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAmWhjIjDvReImNsDnrPDQDUGjifDLeBo',
    appId: '1:398771196913:android:e137b63a12dec647e02a50',
    messagingSenderId: '398771196913',
    projectId: 'metal-air-447106-m3',
    storageBucket: 'metal-air-447106-m3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVnP3Rva76oPFKKiKVEqEniwQxmzFvJ4',
    appId: '1:398771196913:ios:a63f5d979e31ae69e02a50',
    messagingSenderId: '398771196913',
    projectId: 'metal-air-447106-m3',
    storageBucket: 'metal-air-447106-m3.firebasestorage.app',
    androidClientId: '398771196913-4uc291q8l47h9lfutcvqnaf57dvth93j.apps.googleusercontent.com',
    iosClientId: '398771196913-hcvhd038ir2p1u3sbqog12cqbblhdp9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.rencanaReceh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnVnP3Rva76oPFKKiKVEqEniwQxmzFvJ4',
    appId: '1:398771196913:ios:a63f5d979e31ae69e02a50',
    messagingSenderId: '398771196913',
    projectId: 'metal-air-447106-m3',
    storageBucket: 'metal-air-447106-m3.firebasestorage.app',
    androidClientId: '398771196913-4uc291q8l47h9lfutcvqnaf57dvth93j.apps.googleusercontent.com',
    iosClientId: '398771196913-hcvhd038ir2p1u3sbqog12cqbblhdp9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.rencanaReceh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCclD7CKiVK0lL1UjemZzcJ-XHV37mMEqo',
    appId: '1:398771196913:web:c4b5db3d179a80bce02a50',
    messagingSenderId: '398771196913',
    projectId: 'metal-air-447106-m3',
    authDomain: 'metal-air-447106-m3.firebaseapp.com',
    storageBucket: 'metal-air-447106-m3.firebasestorage.app',
  );
}
